# Generated by Django 2.2 on 2021-06-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JadeHourApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
