# Generated by Django 2.2 on 2021-06-17 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JadeHourApp', '0002_remove_product_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
