# Generated by Django 2.2 on 2021-06-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JadeHourApp', '0003_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order_Item',
            new_name='OrderItem',
        ),
        migrations.RenameModel(
            old_name='Shipping_Address',
            new_name='ShippingAddress',
        ),
    ]
